language: cpp

matrix:
    include:
        - os: windows

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install -y wget mono-xbuild libaio-dev;
        sudo apt-get install -y --no-install-recommends libboost-all-dev;
      fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        bash test.sh;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        powershell -ExecutionPolicy Bypass -command "cmd /c test.cmd";
      fi

notifications:
  email: false
