language: cpp

matrix:
    include:
        - os: windows

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install -y wget mono-xbuild libaio-dev;
        sudo apt-get install -y --no-install-recommends libboost-all-dev;
      fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        ./run.sh format;
        ./run.sh start_zk;
        ulimit -c unlimited -S;
        this_path=`readlink -f $0`;
        export DSN_ROOT=`dirname $this_path`;
        ./run.sh build --build_plugins;
        ./run.sh install;
        ./run.sh test;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        powershell;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        SET DSN_AUTO_TEST=1;
        run.cmd setup-env;
        run.cmd build Debug .\build build_plugins;
        run.cmd install Debug .\build;
        run.cmd start_zk;
        run.cmd test Debug .\build;
      fi

notifications:
  email: false
