language: cpp

matrix:
    include:
        - os: linux
          sudo: required
          dist: xenial

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install -y wget mono-xbuild libaio-dev;
        sudo apt-get install -y --no-install-recommends libboost-all-dev;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        run.cmd setup-env
      fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        ./run.sh format;
        ulimit -c unlimited -S;
        this_path=`readlink -f $0`;
        export DSN_ROOT=`dirname $this_path`;
        ./run.sh build --build_plugins;
        ./run.sh install;
        ./run.sh test;
      fi

notifications:
  email: false
